[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000

[rpc_endpoints]
goerli = "https://rpc.ankr.com/eth_goerli"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
